language: ruby
before_script:
- bundle exec rake db:create --all
- bundle exec rake db:migrate
services:
- postgresql
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: hz7H9rcDNVUp5vCbrNVQPsYGSLJdoNkWNG9CXbuEBX+/XWpw00le1by7vsvHhNAyEGLFpLl0sZ5SGXhaI89QJvCqKtPtjAfsz0fcnTB3BHkqJm3EgH0mDC4mwcgGhsDXlqLvqx7qhc+KKyPH4hiz3y4BsLh3bIFHnJNQnIXA3+j/BY6tP8aaMufFkjlDkFJ/KV4E2rLZa9EPIR9c8Knp/P1Dy2D+7AQD4kk/PqxUdNV3KvBmZkYGb2tvWU7FdgN8cKJOm4D16LthTkdtL60UmTfwARLr5YJCvhn/97BP1zd3LpttsWhad9yHNOsO1ULsAZOGduOuZEx1LgLMnn3Lwuj8UZz2GrKR2zL//DR7LfO25pRP6x0DSm/e4Me5cw1IOPu1M5rnxBFp8lcczKPab5oG3FstBIloawS0B4W71UQ3jsM49XSE6Qm9HvGHjlHykiRjfQceFmeX6p9N/JQjNoVEIi+Aebev0Qq5A4hZXxreJeielCRivVEq0vKHEc9YEQVwTfS14ULm/B36Owx1KJP913B2Idi86GMCD70d8GX+MZkRir9bmICCf0MAIJuCDNwWRX7NyHhJrXtPhsVJp949/si+AvSU4pskYpKwXA2Vr9QNLMMFJcXkUm0osE3wAP0IzOHfREhbVD59IK7dt14BcLImGeh70ObgY8HjFco=
  app:
    develop: oddio
    master: oddio
  on:
    repo: chakeresa/oddio
  run:
    - "rails db:migrate"
